# CM2 Numpy - oefening 3

De blokcoördinator D.O. Cent van blok A, SIE-V2  wil graag de cijfers analyseren en verwerken. Het blok bestaat uit 3 vakken, die door 10 studenten gevolgd zijn. Analyse omvat o.a. het bepalen van gemiddelde cijfer, het aantal voldoendes en cursusrendement. De verwerking bestaat uit het corrigeren van de cijfers.

In `blokAcijfers.txt` staan de cijfers per vak (naast elkaar staan de vakken, onder elkaar de studenten):

vak1 | vak2 | vak3
----|-------|------
6.5 | 7.3   | 6.4
8.0 | 8.0	| 8.5
3.2	| 4.0	| 5.0
7.9	| 7.1	| 3.5
7.3	| 7.8	| 8.0
8.6	| 8.0	| 9.0
4.0	| 6.0	| 5.5
7.3	| 7.8	| 7.8
4.5	| 5.6	| 7.7
5.0	| 7.0	| 7.2


In [1]:
import numpy as np

-	Lees tekstbestand: blokAcijfers.txt in, in een numpy array met naam `cijfers`.
-	Laat zien dat de gegevens goed ingelezen zijn.
-	Toon de array attributen.

In [2]:
vCijfers = np.loadtxt("blokAcijfers.txt")

print("Cijfers:\n{}\n".format(vCijfers))

print("Cijfers heeft {} elementen, {} dimensies, de vorm {} en de inhoud is van type {}.\n".format(vCijfers.size, vCijfers.ndim, vCijfers.shape, vCijfers.dtype))

Cijfers:
[[6.5 7.3 6.4]
 [8.  8.  8.5]
 [3.2 4.  5. ]
 [7.9 7.1 3.5]
 [7.3 7.8 8. ]
 [8.6 8.  9. ]
 [4.  6.  5.5]
 [7.3 7.8 7.8]
 [4.5 5.6 7.7]
 [5.  7.  7.2]]

Cijfers heeft 30 elementen, 2 dimensies, de vorm (10, 3) en de inhoud is van type float64.



De docent ziet dat er 2 cijfers fout zijn en wil deze corrigeren
-	Wijzig de volgende cijfers:
    *	vak-2, student-3  cijfer 4.0 moet 4.3 worden.
    *	vak-1, student-10, cijfer 5.0 moet 4.8 worden.

In [3]:
vCijfers[2,1] = 4.3
vCijfers[9,0] = 4.8

print("Verbeterde cijfers:\n{}\n".format(vCijfers))

Verbeterde cijfers:
[[6.5 7.3 6.4]
 [8.  8.  8.5]
 [3.2 4.3 5. ]
 [7.9 7.1 3.5]
 [7.3 7.8 8. ]
 [8.6 8.  9. ]
 [4.  6.  5.5]
 [7.3 7.8 7.8]
 [4.5 5.6 7.7]
 [4.8 7.  7.2]]



De docent wil wat basisgegevens weten.
-	Bepaal minimum, maximum en gemiddelde van alle cijfers.
-	Bepaal minimum, maximum en gemiddelde van elk vak (3 getallen).
-	Bepaal minimum, maximum en gemiddelde van elke student (10 getallen).

In [4]:
print("Van het totaal is het minimum {}, het maximum {} en het gemiddelde {:0.2f}.\n".format(vCijfers.min(), vCijfers.max(), vCijfers.mean()))
print("Van vak 1 is het minimum {}, het maximum {} en het gemiddelde {:0.2f}.".format(vCijfers[:,0].min(), vCijfers[:,0].max(), vCijfers[:,0].mean()))
print("Van vak 2 is het minimum {}, het maximum {} en het gemiddelde {:0.2f}.".format(vCijfers[:,1].min(), vCijfers[:,1].max(), vCijfers[:,1].mean()))
print("Van vak 3 is het minimum {}, het maximum {} en het gemiddelde {:0.2f}.\n".format(vCijfers[:,2].min(), vCijfers[:,2].max(), vCijfers[:,2].mean()))

Van het totaal is het minimum 3.2, het maximum 9.0 en het gemiddelde 6.65.

Van vak 1 is het minimum 3.2, het maximum 8.6 en het gemiddelde 6.21.
Van vak 2 is het minimum 4.3, het maximum 8.0 en het gemiddelde 6.89.
Van vak 3 is het minimum 3.5, het maximum 9.0 en het gemiddelde 6.86.



In [5]:
print("Minimum voor elke student:", np.min(vCijfers, axis=1))
print("Maximum voor elke student:", np.max(vCijfers, axis=1))
print("Gemiddelde voor elke student:", np.around(np.mean(vCijfers, axis=1), 1))

Minimum voor elke student: [6.4 8.  3.2 3.5 7.3 8.  4.  7.3 4.5 4.8]
Maximum voor elke student: [7.3 8.5 5.  7.9 8.  9.  6.  7.8 7.7 7.2]
Gemiddelde voor elke student: [6.7 8.2 4.2 6.2 7.7 8.5 5.2 7.6 5.9 6.3]


De docent wil graag zien wat de cijfers zijn als ze afgerond worden op hele getallen.
-	Kopieer de array naar een nieuwe array.
-	Rond de waarden af.
-	Laat de resultaten zien.

In [6]:
vCijfersRond = vCijfers.copy()
vCijfersRond = np.around(vCijfersRond, 0)

print("\nAfgeronde cijfers:\n{}\n".format(vCijfersRond))


Afgeronde cijfers:
[[6. 7. 6.]
 [8. 8. 8.]
 [3. 4. 5.]
 [8. 7. 4.]
 [7. 8. 8.]
 [9. 8. 9.]
 [4. 6. 6.]
 [7. 8. 8.]
 [4. 6. 8.]
 [5. 7. 7.]]



Er is een fout gemaakt bij de cijfers van het 1e vak. Iedere student krijgt 0.5 punt extra erbij.
-	Vul een ‘ophoogarray’ bestaande uit 3 kolommen en elk 10 rijen en vul deze eerst met 0.0 en daarna de eerste rij met de waarden 0.5.
-	Tel de ophoogarray op bij de cijfer array.

In [7]:
vCijfersVerhoging = np.zeros_like(vCijfers)
vCijfersVerhoging[:, 0] = 0.5

vCijfersNaVerhoging = vCijfers + vCijfersVerhoging

print("\nCijfers na verhoging:\n{}\n".format(vCijfersNaVerhoging))


Cijfers na verhoging:
[[7.  7.3 6.4]
 [8.5 8.  8.5]
 [3.7 4.3 5. ]
 [8.4 7.1 3.5]
 [7.8 7.8 8. ]
 [9.1 8.  9. ]
 [4.5 6.  5.5]
 [7.8 7.8 7.8]
 [5.  5.6 7.7]
 [5.3 7.  7.2]]



De docent wil een lijstje waarin hij in één opslag ziet waar een voldoende (`True`) en waar een onvoldoende (`False`) staat.  
-	Maakt dit lijstje.

In [8]:
print(vCijfers >= 5.5)

[[ True  True  True]
 [ True  True  True]
 [False False False]
 [ True  True False]
 [ True  True  True]
 [ True  True  True]
 [False  True  True]
 [ True  True  True]
 [False  True  True]
 [False  True  True]]
